### PR TITLE
definitions: raphael: Install PLATFORM.SOC_QC8150.BATTERY

### PR DESCRIPTION
**Pull request by qaz6750**
* This submission fixes the issue of not installing the qcbattminiclass8150 driver by default
* Please note that the qcbattminiclass8150 driver may cause some BSOD situations

### CODE REVIEW

**Comment by degdag** [comment]
Please not that my pm8150b ic get fired after updating  the platform driver in order to get battery driver working. 

I suggest  a deep test before enabling or missing with battery on Raphael at all

**Comment by sunflower2333** [comment]
@degdag fired?

**Comment by degdag** [comment]
> @degdag fired?

Yes Burnt. it's completely broken I have to replace the ic

**Comment by qaz6750** [comment]
The latest qcbattminiclass8150 driver has never experienced a similar situation on Cepheus. But in order to avoid BSOD issues, both Cepheus and Nabu were downgraded to version 1680.

I think this may require investigation

**Comment by sunflower2333** [comment]
@qaz6750 RIP PM8150B

**Pull request closed without merging**
